### PR TITLE
Add 5 minute version of BP debating

### PR DESCRIPTION
**Pull request by tswsl1989**
Add 5 minute British Parliamentary variant with 15 minutes prep time

### CODE REVIEW

**Comment by czlee** [comment]
Thanks for the pull request!  Forgive my ignorance, but would you fill me in on where 5-minute BP is used?

**Comment by tswsl1989** [comment]
I've come across it at smaller IVs/Opens and novice competitions in the UK. We also use it within my society. Wasn't sure if that was significant enough to mention in the usedat tag or not.

**Comment by czlee** [comment]
I see, fair enough. I haven't actually (before now) considered what to do with the `<usedat>` tag in that situation. Is there one or two (or three) of those competitions that are the most significant among them? Major novice tournaments totally count, especially if it's mainly a novice format (like Thropy in NZ).

Basically I think it'd be neat just to give people a rough idea of where it's used, if it's easy enough to describe :-)  If there aren't three or less that spring to mind then a descriptor like "Novice competitions in the UK" might work too.  If it wouldn't really fit then that's cool too, no biggie!

**Comment by tswsl1989** [comment]
How about that?

**Comment by czlee** [comment]
Looking good, thanks!

**Comment by czlee** [comment]
I'll probably release it early next month (reluctant to do updates during WUDC in case something goes wrong). Thanks for the contribution, it's interesting to know about different formats used around the world too.

**Comment by czlee** [comment]
Just letting you know, I'm releasing it now without the prep time to keep it consistent with the other styles (Easters is an exception because the chair runs prep time in that style), but I'm starting work on new features and the first one I'll be doing is a proper prep timer (as opposed to a hacked speech timer) so hopefully it won't be too long before it's a thing :-)

Anyone who already has this file on their phone will find it won't be affected by the update when it comes, because user files override built-in files when they have the same name.

**Comment by tswsl1989** [comment]
Excellent, cheers :)

**Pull request merged**
